name: BedWars-Underworld
description: An addon for BedWars that adds the Rush gamemode.
version: '${project.version}'
author: ritana5
contributors:
  - Kiiya
  - Happy_FZM
  - Zuyte
main: net.ritana5.underworld.Underworld
api-version: "1.13"
softdepend:
  - BedWars1058
  - BedWars2023
  - hCore
commands:
  bw:
    description: "Manage iron ingots for players."
    usage: "/bw <givesouls/removesouls> <player> <amount>"